services:
  - type: web
    name: urban-flood-monitor
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true